# Generated by Django 3.0.7 on 2020-06-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_areas_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasEspecificas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_formula', models.CharField(max_length=200)),
                ('formula', models.CharField(max_length=500)),
                ('nome_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_area', to='pages.Areas')),
            ],
        ),
    ]
