# Generated by Django 3.0.7 on 2020-06-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasespecificas',
            name='casos_uso',
            field=models.CharField(default='.', max_length=500),
        ),
    ]
